name: easy_hr
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  equatable: ^2.0.5
  dio: ^5.2.1+1
  dartz: ^0.10.1
  bloc: ^8.1.2
  get_it: ^7.6.7
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  google_fonts: ^4.0.4
  shared_preferences: ^2.2.2
  dropdown_search: ^5.0.6
  flutter_screenutil: ^5.7.0
  fluttertoast: ^8.2.4
  shimmer: ^3.0.0
  pretty_dio_logger: ^1.3.1

  flutter_localizations:
    sdk: flutter
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/static/Cairo-Light.ttf
          weight: 200
        - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf
          weight: 700